# Generated by Django 6.0.3 on 2026-03-30 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_loja_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loja',
            options={'ordering': ['nome'], 'verbose_name': 'Loja', 'verbose_name_plural': 'Lojas'},
        ),
    ]
