# Generated by Django 5.1.15 on 2026-04-26 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_loja_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.loja', verbose_name='Loja'),
        ),
    ]
