# Generated by Django 6.0.3 on 2026-03-30 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_imagem'),
        ('core', '0004_alter_loja_options'),
    ]

    operations = [
    ]
