# Generated by Django 5.1.15 on 2026-04-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_produto_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='lojas/', verbose_name='Imagem da loja'),
        ),
    ]
